<img src="../assets/ga-logo.png" style="float: left; margin: 20px; height: 55px">

# Exercise - `pandas` Data Transformation

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

## Part A: Load and Clean

#### 1. Load `College.csv`

- The first column doesn't have an accurate name, rename it.

In [2]:
# Your code here
College = pd.read_csv('data/College.csv')

#### 2. Check the shape, the data types of each column, and the number of missing values per column

In [3]:
# Your code here
College.shape

(777, 19)

#### 3. Fix the `PhD` column

- `PhD` is the percentage of faculty with a PhD, but it has inaccurate entries.
- Fix the column and fill these entries with the plausible values.

In [4]:
# Your code here
College.head()

,Unnamed: 0,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

In [5]:
College.dtypes

Unnamed: 0         str
Private            str
Apps             int64
Accept           int64
Enroll           int64
Top10perc        int64
Top25perc        int64
F.Undergrad      int64
P.Undergrad      int64
Outstate         int64
Room.Board       int64
Books            int64
Personal         int64
PhD                str
Terminal         int64
S.F.Ratio      float64
perc.alumni      int64
Expend           int64
Grad.Rate        int64
dtype: object

In [6]:
College.isnull().sum()

Unnamed: 0     0
Private        0
Apps           0
Accept         0
Enroll         0
Top10perc      0
Top25perc      0
F.Undergrad    0
P.Undergrad    0
Outstate       0
Room.Board     0
Books          0
Personal       0
PhD            0
Terminal       0
S.F.Ratio      0
perc.alumni    0
Expend         0
Grad.Rate      0
dtype: int64

In [7]:
# Replace ? with missing value
College['PhD'] = College['PhD'].replace('?', np.nan)

# Convert the column to numbers
College['PhD'] = pd.to_numeric(College['PhD'], errors='coerce')

# Convert percentage values to decimals
College['PhD'] = College['PhD'] / 100

In [8]:
College.head(20)

,Unnamed: 0,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,0.70,78,18.1,12,7041,60
1,Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,0.29,30,12.2,16,10527,56
2,Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,0.53,66,12.9,30,8735,54
3,Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,0.92,97,7.7,37,19016,59
4,Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,0.76,72,11.9,2,10922,15
5,Albertson College,Yes,587,479,158,38,62,678,41,13500,3335,500,675,NaN,73,9.4,11,9727,55
6,Albertus Magnus College,Yes,353,340,103,17,45,416,230,13290,5720,500,1500,0.90,93,11.5,26,8861,63
7,Albion College,Yes,1899,1720,489,37,68,1594,32,13868,4826,450,850,0.89,100,13.7,37,11487,73
8,Albright College,Yes,1038,839,227,30,63,973,306,15595,4400,300,500,0.79,84,11.3,23,11644,80
9,Alderson-Broaddus College,Yes,582,498,172,21,44,799,78,10468,3380,660,1800,0.40,41,11.5,15,8991,52
10,Alfred University,Yes,1732,1425,472,37,75,1830,110,16548,5406,500,600,0.82,88,11.3,31,10932,73
11,Allegheny College,Yes,2652,1900,484,44,77,1707,44,17080,4440,400,600,0.73,91,9.9,41,11711,76
12,Allentown Coll. of St. Francis de Sales,Yes,1179,780,290,38,64,1130,638,9690,4785,600,1000,0.60,84,13.3,21,7940,74
13,Alma College,Yes,1267,1080,385,44,73,1306,28,12572,4552,400,400,0.79,87,15.3,32,9305,68
14,Alverno College,Yes,494,313,157,23,46,1317,1235,8352,3640,650,2449,0.36,69,11.1,26,8127,55
15,American International College,Yes,1420,1093,220,9,22,1018,287,8700,4780,450,1400,0.78,84,14.7,19,7355,69
16,Amherst College,Yes,4302,992,418,83,96,1593,5,19760,5300,660,1598,NaN,98,8.4,63,21424,100
17,Anderson University,Yes,1216,908,423,19,40,1819,281,10100,3520,550,1100,0.48,61,12.1,14,7994,59
18,Andrews University,Yes,1130,704,322,14,23,1586,326,9996,3090,900,1320,0.62,66,11.5,18,10908,46
19,Angelo State University,No,3540,2001,1016,24,54,4190,1512,5130,3592,500,2000,0.60,62,23.1,5,4010,34

#### 4. Fix the `Grad.Rate` column

- `Grad.Rate` is the graduation rate, but it has data entry errors.

In [9]:
# Your code here
# Convert the column to numbers
College['Grad.Rate'] = pd.to_numeric(College['Grad.Rate'], errors='coerce')

# Convert percentage values to decimals
College['Grad.Rate'] = College['Grad.Rate'] / 100

In [10]:
College.head(20)

,Unnamed: 0,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,0.70,78,18.1,12,7041,0.60
1,Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,0.29,30,12.2,16,10527,0.56
2,Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,0.53,66,12.9,30,8735,0.54
3,Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,0.92,97,7.7,37,19016,0.59
4,Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,0.76,72,11.9,2,10922,0.15
5,Albertson College,Yes,587,479,158,38,62,678,41,13500,3335,500,675,NaN,73,9.4,11,9727,0.55
6,Albertus Magnus College,Yes,353,340,103,17,45,416,230,13290,5720,500,1500,0.90,93,11.5,26,8861,0.63
7,Albion College,Yes,1899,1720,489,37,68,1594,32,13868,4826,450,850,0.89,100,13.7,37,11487,0.73
8,Albright College,Yes,1038,839,227,30,63,973,306,15595,4400,300,500,0.79,84,11.3,23,11644,0.80
9,Alderson-Broaddus College,Yes,582,498,172,21,44,799,78,10468,3380,660,1800,0.40,41,11.5,15,8991,0.52
10,Alfred University,Yes,1732,1425,472,37,75,1830,110,16548,5406,500,600,0.82,88,11.3,31,10932,0.73
11,Allegheny College,Yes,2652,1900,484,44,77,1707,44,17080,4440,400,600,0.73,91,9.9,41,11711,0.76
12,Allentown Coll. of St. Francis de Sales,Yes,1179,780,290,38,64,1130,638,9690,4785,600,1000,0.60,84,13.3,21,7940,0.74
13,Alma College,Yes,1267,1080,385,44,73,1306,28,12572,4552,400,400,0.79,87,15.3,32,9305,0.68
14,Alverno College,Yes,494,313,157,23,46,1317,1235,8352,3640,650,2449,0.36,69,11.1,26,8127,0.55
15,American International College,Yes,1420,1093,220,9,22,1018,287,8700,4780,450,1400,0.78,84,14.7,19,7355,0.69
16,Amherst College,Yes,4302,992,418,83,96,1593,5,19760,5300,660,1598,NaN,98,8.4,63,21424,1.00
17,Anderson University,Yes,1216,908,423,19,40,1819,281,10100,3520,550,1100,0.48,61,12.1,14,7994,0.59
18,Andrews University,Yes,1130,704,322,14,23,1586,326,9996,3090,900,1320,0.62,66,11.5,18,10908,0.46
19,Angelo State University,No,3540,2001,1016,24,54,4190,1512,5130,3592,500,2000,0.60,62,23.1,5,4010,0.34

In [11]:
College.dtypes

Unnamed: 0         str
Private            str
Apps             int64
Accept           int64
Enroll           int64
Top10perc        int64
Top25perc        int64
F.Undergrad      int64
P.Undergrad      int64
Outstate         int64
Room.Board       int64
Books            int64
Personal         int64
PhD            float64
Terminal         int64
S.F.Ratio      float64
perc.alumni      int64
Expend           int64
Grad.Rate      float64
dtype: object

## Part B: Diagnose, Transform, and Visualize Skew

#### The tables bellow can be used as a reference to classify the the degree and distribution of the skewness as well as the right distribution transformation method.

### Table1: Skewness Score Interpretation

| Skewness Score Range | Distribution Shape | 
| :--- | :--- | 
| **Less than -1** | Highly Skewed (Left) | 
| **Between -1 and -0.5** | Moderately Skewed (Left) | 
| **Between -0.5 and 0.5** | `Normal (Symmetrical)` | 
| **Between 0.5 and 1** | Moderately Skewed (Right) | 
| **Greater than 1** | Highly Skewed (Right) |

### Table2: Decision Matrix: Choosing the Right Distribution Transformation

| Transformation | Best Data Shape / Scenario | Handles Zeros? | Handles Negatives? | Impact on Linear Models / Interpretability |
| :--- | :--- | :--- | :--- | :--- |
| **Log Plus One ($\log(x+1)$)** | Highly Right-Skewed with zero counts |  Yes | ❌ No | Safely maps zero values to zero while retaining standard log-compression benefits. |
| **Box-Cox** | Right or Left Skewed (Strictly positive) | ❌ No | ❌ No | Automatically searches for the mathematically ideal power exponent ($\lambda$) to maximize normality. |
| **Yeo-Johnson** | Right or Left Skewed (Versatile) |  Yes |  Yes | Modifies the Box-Cox algorithm to safely calculate ideal power scales across zeros and negatives. |

#### 5. Write `skew_calc()` with `%%writefile`, then `plot_transformations()` here

- `skew_calc(df)`: for every numeric column, calculate its skewness, classify the degree and direction, and recommend a transformation. Use `%%writefile` to save this into `myutils.py`, then import it.
- `plot_transformations(df, skew_table)`: take a DataFrame together with the output of `skew_calc()`, apply the **best** recommended transformation to each column, and plot the before and after distributions side by side with the skewness labeled on each subplot.

In [12]:
%%writefile myutils.py
import numpy as np
import pandas as pd



def skew_calc(df):
    """
    Diagnoses skewness for every numeric column in a DataFrame and recommends a transformation based on the column's skewness and
    minimum value. Binary, encoded, and ID columns are excluded, since skewness isn't a meaningful for them.
    It returns a DataFrame with the following columns:
    Feature, Skewness, Degree, Direction, Recommended Transformation
    """
    # Your code here 
    results = []

    # Select numeric columns only
    numeric_columns = df.select_dtypes(include=np.number).columns

    for column in numeric_columns:

        clean_column = df[column].dropna()
        unique_count = clean_column.nunique()

        # Skip empty or constant columns
        if unique_count <= 1:
            continue

        # Skip binary columns
        if unique_count == 2:
            continue

        # Skip common ID/index columns
        column_lower = column.lower()

        if (
            column_lower == "id"
            or column_lower.endswith("_id")
            or column_lower.startswith("id_")
        ):
            continue

        # Calculate skewness
        skewness = clean_column.skew()
        absolute_skewness = abs(skewness)
        minimum_value = clean_column.min()

        # Determine direction
        if skewness > 0:
            direction = "Right"
        elif skewness < 0:
            direction = "Left"
        else:
            direction = "Symmetric"

        # Determine degree and recommended transformation
        if absolute_skewness < 0.5:
            degree = "Approximately symmetric"
            transformation = "None"

        elif absolute_skewness < 1:
            degree = "Moderately skewed"

            #
            if skewness > 0 and minimum_value >= 0:
                transformation = "Square root"
            elif skewness < 0 and minimum_value >= 0:
                transformation = "Square"
            #if min<0 we should use Yeo
            else:
                transformation = "Yeo-Johnson"

        
        else:
            degree = "Highly skewed"

            #if there is not negative values do: 
            if skewness > 0 and minimum_value >= 0:
                transformation = "Try Log1p first; if skewness remains high, try Box-Cox"
            #if there is negative values do yeo:
            else:
                transformation = "Yeo-Johnson"

        #
        results.append({
            "Feature": column,
            "Skewness": skewness,
            "Degree": degree,
            "Direction": direction,
            "Recommended Transformation": transformation
        })

    skew_table = pd.DataFrame(results)

    if not skew_table.empty:
        skew_table["Skewness"] = skew_table["Skewness"].round(3)

    return skew_table

Overwriting myutils.py

In [13]:
# Now import the function from myutils
import myutils
results = myutils.skew_calc(College)
results

,Feature,Skewness,Degree,Direction,Recommended Transformation
0,Apps,3.724,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
1,Accept,3.418,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
2,Enroll,2.690,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
3,Top10perc,1.413,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
4,Top25perc,0.259,Approximately symmetric,Right,None
5,F.Undergrad,2.610,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
6,P.Undergrad,5.692,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
7,Outstate,0.509,Moderately skewed,Right,Square root
8,Room.Board,0.477,Approximately symmetric,Right,None
9,Books,3.485,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
10,Personal,1.742,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
11,PhD,-0.756,Moderately skewed,Left,Square
12,Terminal,-0.817,Moderately skewed,Left,Square
13,S.F.Ratio,0.667,Moderately skewed,Right,Square root
14,perc.alumni,0.607,Moderately skewed,Right,Square root
15,Expend,3.459,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
16,Grad.Rate,-0.114,Approximately symmetric,Left,None

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import PowerTransformer


def plot_transformations(df, skew_table):
    """
    Applies the recommended transformation to each column and plots
    the original and transformed distributions side by side.

    Returns a transformed copy of the DataFrame.
    """


    # Go through every row in the skewness table
    for index, row in skew_table.iterrows():

        feature = row["Feature"]
        transformation = row["Recommended Transformation"]
        valid_mask = df[feature].notna()
        original = df.loc[valid_mask, feature].astype(float)
        
        # Apply the recommended transformation
        if transformation == "None":
            transformed = original.copy()

        elif transformation == "Square root":
            transformed = np.sqrt(original)

        elif transformation == "Square":
            transformed = np.square(original)

        elif transformation == "Log1p":
            transformed = np.log1p(original)

        elif transformation == "Yeo-Johnson":
            pt = PowerTransformer(
                method="yeo-johnson",
                standardize=False
            )

            transformed_values = pt.fit_transform(orginal)

            transformed = pd.Series(
                transformed_values,
                index=original.index
            )

            
        elif transformation == "Try Log1p first; if skewness remains high, try Box-Cox":

            # Try Log1p first
            log_transformed = np.log1p(original)
            log_skewness = log_transformed.skew()

            # If Log1p is still highly skewed, try Box-Cox
            if abs(log_skewness) > 0.5:

                # Box-Cox requires values greater than zero
                boxcox_original = original + 1

                pt = PowerTransformer(
                    method="box-cox",
                    standardize=False
                )

                transformed_values = pt.fit_transform(
                    boxcox_original.to_numpy().reshape(-1, 1)
                ).flatten()

                transformed = pd.Series(
                    transformed_values,
                    index=original.index
                )

                transformation = "Box-Cox"

            else:
                transformed = log_transformed
                transformation = "Log1p"


        
        else:
            transformed = original.copy()

        # Store the transformed values
        transformed_df[feature+' transform'] = transformed

        # Calculate skewness before and after
        before_skew = original.skew()
        after_skew = transformed.skew()

        # Plot both distributions
        fig, axes = plt.subplots(1, 2, figsize=(12, 4))

        sns.histplot(original, kde=True, ax=axes[0])
        axes[0].set_title(
            f"{feature} — Before\nSkewness = {before_skew:.3f}"
        )
        axes[0].set_xlabel(feature)

        sns.histplot(transformed, kde=True, ax=axes[1])
        axes[1].set_title(
            f"{feature} — After {transformation}\n"
            f"Skewness = {after_skew:.3f}"
        )
        axes[1].set_xlabel(feature)

        plt.tight_layout()
        plt.show()

    return transformed_df

#### 6. Run the functions on your cleaned DataFrame

- Call `skew_calc()` and check the table, does the classification match what you expected for these features?
- Call `plot_transformations()`, is the change significant?

In [15]:
# Your code here
import myutils
skew_table = myutils.skew_calc(College)
skew_table

,Feature,Skewness,Degree,Direction,Recommended Transformation
0,Apps,3.724,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
1,Accept,3.418,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
2,Enroll,2.690,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
3,Top10perc,1.413,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
4,Top25perc,0.259,Approximately symmetric,Right,None
5,F.Undergrad,2.610,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
6,P.Undergrad,5.692,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
7,Outstate,0.509,Moderately skewed,Right,Square root
8,Room.Board,0.477,Approximately symmetric,Right,None
9,Books,3.485,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
10,Personal,1.742,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
11,PhD,-0.756,Moderately skewed,Left,Square
12,Terminal,-0.817,Moderately skewed,Left,Square
13,S.F.Ratio,0.667,Moderately skewed,Right,Square root
14,perc.alumni,0.607,Moderately skewed,Right,Square root
15,Expend,3.459,Highly skewed,Right,"Try Log1p first; if skewness remains high, try..."
16,Grad.Rate,-0.114,Approximately symmetric,Left,None

In [16]:
# Your code here
Collage_Transform = plot_transformations(College, skew_table)

NameError: name 'transformed_df' is not defined

## Part C: Apply the transformations

#### 7. Create transformed versions of the skewed columns

- Create a new column for each of the skewed columns based on the recommendations.

In [ ]:
trans_cols = []


# Your code here 
# Already Created in the funtion 
Collage_Transform

## Part D: Feature Engineering and Encoding

#### 8. Engineer a new feature called `Accept_Rate`

- An acceptance rate is more meaningful than the counts of applicants and accepted students on their own.

In [ ]:
# Your code here 
Collage_Transform ['Accept_Rate'] = Collage_Transform['Accepttransform'] /Collage_Transform['Appstransform']

In [ ]:
Collage_Transform

#### 9. Bin `Outstate` into a new column called `Outstate_Tier`

- Use `pd.cut()` to split out-of-state tuition into bins.

In [ ]:
# Your code here 
Collage_Transform["Outstate_Tier"] = pd.cut(
    Collage_Transform["Outstate"],
    bins=3,
    labels=["Low", "Medium", "High"]
)

Collage_Transform

#### 10. Ordinally encode `Outstate_Tier`

- Create a new column that maps the tiers ordinally.

In [ ]:
# Your code here 

Collage_Transform["Outstate_Tier"] = (
    Collage_Transform["Outstate_Tier"]
    .map({
        "Low": 0,
        "Medium": 1,
        "High": 2
    })
)

Collage_Transform

#### 11. Binary encode `Private`

- Create a new coumn that maps `Yes` to 1 and `No` to 0.

In [ ]:
# Your code here 
Collage_Transform["Private"] = (
    Collage_Transform["Private"]
    .map({
        "Yes": 1,
        "No": 0
    })
)

## Part E: Scale and Explore

#### 12. Standardize the transformed and encoded features

- Use `StandardScaler` on all transformed columns from question 7, plus the encoded features and store the results in new columns.

In [ ]:
cols_to_scale = []

# Your code here 
scaler = StandardScaler()

transform_columns = [
    'Appstransform',
    'Accepttransform',
    'Enrolltransform',
    'Top10perctransform',
    'Top25perctransform',
    'F.Undergradtransform',
    'P.Undergradtransform',
    'Outstatetransform',
    'Room.Boardtransform',
    'Bookstransform',
    'Personaltransform',
    'PhDtransform',
    'Terminaltransform',
    'S.F.Ratiotransform',
    'perc.alumnitransform',
    'Expendtransform',
    'Grad.Ratetransform'
]

cols_to_scale = transform_columns + [
    "Accept_Rate",
    "Private",
    "Outstate_Tier"
]

scaled_values = scaler.fit_transform(
    Collage_Transform[cols_to_scale]
)

scaled_column_names = [
    col + "_scaled"
    for col in cols_to_scale
]

Collage_Transform[scaled_column_names] = scaled_values

Collage_Transform.head()

#### 13. Plot a correlation heatmap of your numeric features

- Include the scaled columns from question 12 along with other columns
- Which features look most related to `Grad.Rate`?
- Check and drop highly correlated features

In [ ]:
# Your code here 
numeric_df = Collage_Transform.select_dtypes(include='number')
corr = numeric_df.corr()

plt.figure(figsize=(18, 14))

sns.heatmap(
    corr,
    cmap="coolwarm",
    annot=False
)

plt.title("Correlation Heatmap")
plt.show()

corr["Grad.Rate"].sort_values(ascending=False)

## Part F: Does the Transformation Help?

#### 14. Split your data into train and test sets

- Train the model twice: once using the untransformed columns, and once using the transformed versions, so we can see whether the transformation actually improved the fit
- In both cases, the target will be `Grad.Rate`

In [ ]:
# Your code here

#### 15. Fit a linear regression using the raw predictors

In [45]:
untrans_predictors = []

# Your code here

#### 16. Fit the same model using the log-transformed predictors

In [46]:
trans_predictors = []

# Your code here

#### 17. Compare the two R-squared scores

- Is there an improvement in the results?

In [47]:
# Your code here

#### 18. Export your cleaned and transformed `DataFrame` to a new CSV file called `college_transformed.csv`

In [48]:
# Your code here